# Generated by Django 5.1.6 on 2025-02-24 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='items',
            new_name='item',
        ),
    ]
