# Generated by Django 5.1.6 on 2025-03-04 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'General Inquiry', 'verbose_name_plural': 'General Inquiries'},
        ),
    ]
