# Generated by Django 5.1.6 on 2025-02-24 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_title_service_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicefeature',
            name='service',
        ),
        migrations.DeleteModel(
            name='ServiceGallery',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceFeature',
        ),
    ]
