# Generated by Django 5.1.6 on 2025-02-24 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_price_max_alter_service_price_min_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price_max',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price_min',
        ),
        migrations.RemoveField(
            model_name='service',
            name='size',
        ),
        migrations.RemoveField(
            model_name='service',
            name='type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='usage',
        ),
    ]
