# Generated by Django 5.1.6 on 2025-02-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_item_display_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='display_type',
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('signage', 'Signage'), ('display_design', 'Display Design'), ('digital_printing', 'Digital Printing'), ('vehicle_signs', 'Vehicle Signs')], default='signage', max_length=150),
        ),
    ]
