# Generated by Django 5.1.6 on 2025-02-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_item_display_type_alter_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('signage', 'Signage'), ('display_signs', 'Display Signs'), ('digital_printing', 'Digital Printing'), ('vehicle_signs', 'Vehicle Signs')], default='signage', max_length=150),
        ),
    ]
